import React from "react";

const Strings = {
  LOGOUT_TITLE: "Logout",
  MENU_DASHBOARD_TITLE: "Dashboard",
  MENU_PRODUCTS_TITLE: "Products",
  MENU_CATEGORIESS_TITLE: "Categories",
  MENU_USERS_TITLE: "Users",
  MENU_PRESENTATIONSS_TITLE: "Presentations",
  MENU_PRESENTATIONS_HISTORY_TITLE: "Presentations History",
  COLUMN_DATA_SOURCE_TITLE: "Source",
  COLUMN_NAME: "Name",
  COLUMN_SOURCE: "Source",
  COLUMN_ADDRESS: "Address",
  COLUMN_CONNECTION_TYPE: "Type",
  COLUMN_EMAIL: "Email",
  COLUMN_MOBILE_NUMBER: "Mobile Number",
  COLUMN_PHONE_NUMBER: "Phone Number",
  COLUMN_CLINIC_PHONE_NUMBER: "clinic Phone Number",
  COLUMN_ANNIVERSARY_DATE: "Anniversary Date",
  COLUMN_PRESENTATION_DATE: "Presentation Date",
  COLUMN_PRESENTATION_PRODUCTS: "Presentation Products",
  COLUMN_DATE_OF_BIRTH: "Date Of Birth",
  COLUMN_PROTOCOL: "Protocol",
  COLUMN_HOST: "Host",
  COLUMN_MRP: "MRP",
  COLUMN_USER_NAME: "User Name",
  COLUMN_PASSWORD: "Password",
  COLUMN_PRODUCT_IMAGES: "Product Images",
  COLUMN_PORT: "Port",
  COLUMN_DATA_CONNECTION_TITLE: "Connection",
  COLUMN_DATA_CONNECTION_SOURCE: "Source",
  COLUMN_JOB_STATUS: "Job Status",
  COLUMN_JOB_TYPE: "Job Type",
  COLUMN_JOB_NAME: "Job Name",
  COLUMN_JOBS_SOURCE: "Source",
  COLUMN_JOB_TAGS: "Tags",
  COLUMN_JOB_RISKCORE_IMPORT: "Riskcore Import Template",
  COLUMN_JOB_SCHEDULING_TITLE: "Jobs",
  COLUMN_APPLICATION_NAME: "Name",
  COLUMN_DESCRIPTION: "Description",
  COLUMN_APPLICATION_TITLE: "Application",
  COLUMN_TAG_TYPE: "Tag Name",
  COLUMN_TAG_TITLE: "Tags",
  COLUMN_ROLES_ROLE_NAME: "Role Name",
  COLUMN_ROLES_ROLE_DESCRIPTION: "Role Description",
  COLUMN_ROLES_USERS: "Users",
  COLUMN_ROLES_PERMISSION: "Permissions",
  COLUMN_ROLES_TITLE: "Roles",
  COLUMN_USERS_USER_NAME: "User Name",
  COLUMN_FIRST_NAME: "First Name",
  COLUMN_LAST_NAME: "Last Name",
  COLUMN_USERS_EMAIL: "Email",
  COLUMN_USERS_DEPARTMENT: "Department",
  COLUMN_USERS_USER_ROLE: "User Role",
  COLUMN_USERS_TITLE: "Users",
  COLUMN_USERS_IS_ACTIVE: "Active",
  COLUMN_PRODUCT_IS_ACTIVE: "Active",
  COLUMN_CALENDAR_NAME: "Calendar Name",
  COLUMN_CALENDAR_YEAR: "Calendar Year",
  COLUMN_CALENDAR_FREQUENCY_TAG: "Frequency Tsg",
  COLUMN_CALENDAR_TITLE: "Calendar",
  COLUMN_APPLICATION_TEMPLATE_TEMP_NAME: "Application Template Name",
  COLUMN_APPLICATION_TEMPLATE_NAME: "Application Name",
  COLUMN_APPLICATION_TEMPLATE_FEILD_MAPPING_COUNT: "Feild Mapping Count",
  COLUMN_APPLICATION_TEMPLATE_TITLE: "Application Template",
  COLUMN_INSIGHTS_ID: "ID",
  COLUMN_INSIGHTS_JOB_NAME: "Job Name",
  COLUMN_INSIGHTS_SOURCE: "Source",
  COLUMN_INSIGHTS_TAGS: "Tags",
  COLUMN_INSIGHTS_FILE_EXPECTED_RCV_DATE: "File Expected Received Date",
  COLUMN_INSIGHTS_FILE_EXPECTED_FREQ_TYPE: "File Expected Frequency Type",
  COLUMN_INSIGHTS_REPORT_EFFECTIVE_DATE_AS_AT:
    "Report(Expected) Effective Date As At",
  COLUMN_INSIGHTS_REPORT_EFFECTIVE_DATE_FROM:
    "Report(Expected) Effective Date From",
  COLUMN_INSIGHTS_REPORT_EFFECTIVE_DATE_TO:
    "Report(Expected) Effective Date To",
  COLUMN_INSIGHTS_PMS_STATUS_TYPE: "PMS Status Type",
  COLUMN_INSIGHTS_PMS_STATUS_DATE: "PMS Status Date",
  COLUMN_INSIGHTS_FILE_DELIVERY_STATUS: "File Delivery Status",
  COLUMN_INSIGHTS_DATA_LOAD_STATUS: "Data Load Status",
  COLUMN_INSIGHTS_DATA_LOAD_DATE: "Data Load Date",
  COLUMN_INSIGHTS_NOTE: "Note",
  COLUMN_INSIGHTS_MANUAL_RUN: "Manual Run",
  COLUMN_INSIGHTS_TITLE: "Insights",
  COLUMN_REMEDIAL_ACTION_JOB_ID: "Job Id",
  COLUMN_REMEDIAL_ACTION_JOB_NAME: "Job Name",
  COLUMN_REMEDIAL_ACTION_SOURCE: "Source",
  COLUMN_REMEDIAL_ACTION_TAGS: "Tags",
  COLUMN_REMEDIAL_ACTION_RISKCORE_IMP_TEMPLATE: "RiskCore Import Template",
  COLUMN_REMEDIAL_ACTION_RECEIVED_DATE: "Received Date",
  COLUMN_REMEDIAL_ACTION_EF_REPORT_DATE: "EF Report Date",
  COLUMN_REMEDIAL_ACTION_STATUS_DATE: "Status Date",
  COLUMN_REMEDIAL_ACTION_STATUS: "Status",
  COLUMN_REMEDIAL_ACTION_RUN: "Run",
  COLUMN_REMEDIAL_ACTION_TITLE: "Remedial Action",
  SCHEDULER_SETTINGS_TITLE: "SCHEDULAR SETTINGS",
  EMAI_SETTING_TITLE: "EMAIL SETTING",
  COLUMN_FIELD_NAME: "Field Name",
  IMPORT: "IMPORT",
  EXPORT: "EXPORT",
  HELP_RELEASE_NOTES: "Release Notes",
  HELP_TITLE: "Help",
  HELP_RESOURCES: "Resources",
  HELP_WHERE_TO_NEXT: "Where to next?",
  JOB_SCHEDULING_TITLE: "Job Scheduling: ",
  COLUMN_JOBROLE_BASEDON: "Based On",
  COLUMN_JOBROLE_CHECK_IN: "Check In",
  COLUMN_JOBROLE_CELL_OR_HEADER: "Cell Or Header",
  COLUMN_JOBROLE_CELL_OR_HEADER_VALUE: "Cell Or Header Value",
  COLUMN_JOBROLE_OPERATION: "Operation",
  COLUMN_JOBROLE_SEARCH_VALUE: "Search Value",
  COLUMN_JOBROLE_READ_FROM_NEXT_COLCELL: "Read From Next ColCell",
  COLUMN_JOBROLE_SHEET_NAME: "Sheet Name",
  JOBS_FILE_EXPECTED_RECEIVE_DATE: "File Expected Receive Date",
  JOBS_STEPS_TITLE: "Job Name: ",
  COMPLETE: "Complete",
  COLUMN_BASED_ON: "Based On",
  COLUMN_CHECK_IN: "Check In",
  COLUMN_CELL_OR_HEADER: "Cell Or Header",
  COLUMN_CELL_OR_HEADER_VALUE: "Cell Or Header Value",
  COLUMN_OPERATION: "Operation",
  COLUMN_SEARCH_VALUE: "Search Value",
  COLUMN_READ_FROM_NEXT_COLCELL: "Read From Next ColCell",
  COLUMN_SHEET_NAME: "Sheet Name",
  COLUMN_PRIORITY_ORDER: "Priority Order",
  COLUMN_WIDGET_NAME: "Widget Name",
  COLUMN_PARAMETER: "Parameter",
  COLUMN_LOCATION: "Location",
  COLUMN_FIELD_DESCRIPTION: "Field Description",
  COLUMN_ENABLED: "Enabled",
  COLUMN_ID: "#",
  COLUMN_PRODUCT_ID: "Product Id",
  COLUMN_PRESENTATION_ID: "Presentation Id",
  COLUMN_REPORT_HEADER: "Report Header",
  COLUMN_DATA_TYPE: "Data Type",
  COLUMN_CONNECTION_NAME: "Connection Name",
  COLUMN_DELIVERY_PATH: "Delivery Path",
  BACK_TO_JOB_LISTING: "Back to Jobs",
  REMOTE_DIR_PATH_LABEL: "\\dms.local\\file\\Risk_FunData_Client\\Citco\\",
  COLUMN_DELIVERY_FILE_NAME: "Delivery File Name",
  COLUMN_FILE_FORMAT: "File Format",
  COLUMN_FEILD_MAPPING: "Feild Mapping",
  COLUMN_DESTINATION_FIELD_NAME: "Destination Field Name",
  COLUMN_SOURCE_FIELD_NAME: "Source Field Name",
  INCOMPLETE: "Incomplete",
  COLUMN_EXPECTED_EFFECTIVE_DATE_FROM: "Expected Effective Date - From",
  COLUMN_EXPECTED_EFFECTIVE_DATE_TO: "Expected Effective Date - To",
  COLUMN_FILE_EFFECTIVE_DATE: "Expected Effective Date - As At",
  COLUMN_FILE_EXPECTED_RECEIVE_DATE: "File Expected Receive Date",
  DELETE_SCHEDULE_DATE:
    "Few Scheduled task might be processed previously. Do you want to delete all the Scheduled task for all the years?",
  DELETE_ALL: "Delete All",
  BACK_TO_CALENDAR_LISTING: "Back to Calendar",

  COLUMN_ERRNO: "No",
  COLUMN_ERRDATE: "Date",
  COLUMN_ERRMESSAGE: "Message",
  SEARCH_REMEDIAL_ACTION: "Search Remedial Action",
  COLUMN_RCSTATUS: "RC Status",
  COLUMN_LOGDATE: "Log Date",
  COLUMN_RCLOGFILE: "RC Log file",
  COLUMN_RCPREVIEW_FILE: "RC Preview File",
  SEARCH_INSIGHT: "Search Insight",
  COLUMN_FAVORITE_NAME: "Favorite Name",
  POSITION_LOAD_OPTION: "Position Load Option",
  COLUMN_INSIGHT_STATUS: "Status",
  COLUMN_INSIGHT_DATETIME: "Date and Time",
  COLUMN_ORIGINAL_FILE: "Original File",
  COLUMN_PREPROCESSED_FILE: "PreProcessed File",
  COLUMN_LOG_FILE: "Log file",
  COLUMN_APPLICATIONNAME: "Application Name",
  COLUMN_DELIVERY_STATUS: "Delivery Status",
  COLUMN_FILE: "File",
  COLUMN_MESSAGE: "Message",
  INSIGHT_ORDERBY_ID: "id",
  INSIGHT_ORDERBY_JOBNAME: "jobName",
  INSIGHT_ORDERBY_SOURCE: "source",
  INSIGHT_ORDERBY_TAGS: "tags",
  INSIGHT_ORDERBY_STRFILEEXPEXTEDRECEIVEDATE: "strFileExpextedReceiveDate",
  INSIGHT_ORDERBY_STREXPECTEDEFFECTIVEDATEASAT: "strExpectedEffectiveDateAsAt",
  INSIGHT_ORDERBY_STREXPECTEDEFFECTIVEDATEFROM: "strExpectedEffectiveDateFrom",
  INSIGHT_ORDERBY_STREXPECTEDEFFECTIVEDATETO: "strExpectedEffectiveDateTo",
  INSIGHT_ORDERBY_PROCESSINGSTATUS: "processingStatus",
  INSIGHT_ORDERBY_DELIVERYSTATUS: "deliveryStatus",
  INSIGHT_ORDERBY_RISKCORESTATUS: "riskCoreStatus",
  INSIGHT_ORDERBY_RISKCORESTATUSDATE: "riskCoreStatusDate",
  INSIGHT_ORDERBY_MANUALRUN: "manualRun",
  SUMMARY_JOBS_OVERVIEW_TITLE: "Jobs Overview",
  SUMMARY_RECENT_JOBS_TITLE: "Recent Jobs",
  SUMMARY_QUICK_LINKS_TITLE: "Quick Links",
  SUMMARY_SYSTEM_OVERVIEW_TITLE: "System Overview",
  SUMMARY_FTP_LABEL: "FTP",
  SUMMARY_SMS_CAPTION: "SMS",
  SUMMARY_COUNT_CAPTION: "Count",
  SUMMARY_REQUIRES_ATTENTION: "Requires attention",

  ADD_PRODUCTS: "Add Products",
  EDIT_PRODUCTS: "Edit Products",
  ADD_PRESENTATION: "Add Presentation",
  EDIT_PRESENTATION: "Edit Presentation",
  MENU_PRODUCTS_TITLE: "Products",
  MENU_DOCTORS_TITLE: "Doctors",
  MENU_DOCTORS_SPECIALIZATION_TITLE: "Specialization",
  COLUMN_PRODUCTS_NAME: "Product Name",
  COLUMN_DESCRIPTION: "Description",
  COLUMN_MRP: "MRP",
  COLUMN_PRODUCTS_IMAGE: "Image",
  COLUMN_DOCTORS_FIRST_NAME: "First Name",
  COLUMN_DOCTORS_LAST_NAME: "Last Name",
  COLUMN_SPECIALIZATION: "Specialization",
  COLUMN_DOCTORS_EMAIL: "Email",
  COLUMN_PHONE: "Phone",
  COLUMN_DOCTORS_ADDRESS: "Address",
  COLUMN_CITY: "City",
  COLUMN_COUNTRY: "Country",
  COLUMN_ORGANIZATION_NAME: "Organization Name",
  COLUMN_STATE: "State",
  COLUMN_USERS_NAME: "Name",
  COLUMN_GENDER: "Gender",
  COLUMN_USERS_PHONE: "Phone",
  COLUMN_DOCTORS_TITLE: "Doctors",
  COLUMNS_DOCTORNAME_TILTLE: "Doctor Name",
  COLUMNS_DOCTOR_EMAIL: "Doctor Email",
  COLUMNS_USERNAME_TILTLE: "User Name",
  COLUMNS_PRESENTATION_TITLE: "Presentation Title",
  COLUMNS_PRESENTATION_HISTORY: " History",
  COLUMNS_PRESENTATION_START_DATE: "Presentation Start Date",
  COLUMNS_PRESENTATION_END_DATE: "Presentation End Date",
  SEARCH_TITLE: "Search",
  PRESENTATION_TITLE: "Presentation Title",
  SEARCH_TITLE_DATERANGE: "Daterange",
  TITLE_CATEGORY: "Category",
  SEARCH_TITLE_PRODUCTS: "Products",
  SEARCH_TITLE_DOCTOR: "Doctor",
  SEARCH_TITLE_USER: "User",
  COLUMN_ACTIVE: "Active",
  ADD_PRODUCT_IMAGES: "Add Product Images",
  COLUMN_DOCTORS_IS_ACTIVE: "Active",
  COLUMN_CATEGORY_NAME: "Category Name",
  COLUMN_SPECIALITY_TITLE: "Speciality",
  FORGOT_PASSWORD: "Forgot Password?",
  BACK_TO_LOGIN: "Back To Login",
  INVALID_LOGIN_DETAILS: " Invalid Login Details!",
  TRY_AGAIN_AFTER_SOME_TIME: "Try Again After Some Time!",
  EMAIL: "Email",
  OTP: "OTP",
  PASSWORD: "Password",
  NEW_PASSWORD: "New Password",
  OLD_PASSWORD: "Old Password",
  NEW_PASSWORD: "New Password",
  CONFIRM_NEW_PASSWORD: "Confirm New Password",
  LOGIN: "Login",
  SEND_OTP: "Send OTP",
  RESET_PASSWORD: "Reset Password",
  ADD_CATEGORY: "Add Category",
  ERROR_DELETING_CATEGORIES: "Error Deleting Categories!",
  CATEGORY_ADDED_SUCCESSFULLY: "Category Added Successfully",
  EDIT_CATEGORY: "Edit Category",
  ADD_CATEGORY: "Add Category",
  EDIT_THIS_EXISTING_CATEGORY: "Edit this existing Category",
  CREATE_A_NEW_CATEGORY: "Create a new Category",
  CATEGORY_NAME_IS_REQUIRED: "Category name is required",
  SCHEDULED_WORKS: "Scheduled Works",
  COMPLETED: "Completed",
  FAILED: "Failed",
  OVERDUE: "Overdue",
  PENDING: "Pending",
  VIEW_DETAILS: "View Details",
  COPYRIGHT: "Copyright @2022 All Rights Reserved by Pragalbh Software",
  UPDATE: "Update",
  SAVE: "Save",
  CREATE: "Create",
  IN_PROGRESS: "In Progress",
  ADD_DOCTOR: "Add Doctor",
  EDIT_APPLICATION: "Edit Application",
  DELETE_APPLICATION: "Delete Application",
  DELETE_CONFIRM: "Are You Sure You Want To Delete ?",
  DELETED_SUCCESSFULLY: "Data Deleted Successfully.",
  ERROR_DELETING: "Error Deleting Data!",
  EDIT_DOCTORS: "Edit Doctors",
  EDIT_IN_EXISTING_DOCTORS: "Edit in existing Doctors",
  CREATE_A_NEW_DOCTORS: "Create a new Doctors",
  FIRST_NAME: "First Name",
  LAST_NAME: "Last Name",
  GENDER: "Gender",
  DOCTORS_GENDER: "Doctors gender",
  SPECIALITY: "Speciality",
  EDIT_PROFILE: "Edit Profile",
  EDIT_THIS_PROFILE: "Edit this Profile",
  EDIT_SPECIALIZATION: "Edit Specialization",
  EDIT_IN_EXISTING_SPECIALIZATION: "Edit in existing Specialization",
  EDIT_IN_EXISTING_USERS: "Edit in existing Users",
  CREATE_A_NEW_SPECIALIZATION: "Create a new Specialization",
  CREATE_A_NEW_USERS: "Create a new Users",
  ADD_SPECIALIZATION: "Add Specialization",
  PHONE: "Phone",
  NAME: "Name",
  USERS_GENDER: "Users gender",
  ERROR_GETTING_DATA: "Error Getting Data!",
  DATA_ADDED_SUCCESSFULLY: "Data Added Successfully.",
  EDITED_SUCCESSFULLY: "Edited Successfully",
  ERROR_OCCURED_WHILE_ADDING_DATA: "Error Occured While Adding Data!",
  ERROR_OCCURED_WHILE_UPLOADING_IMAGE_DATA: "Error Occured While Uploading Image  Data!",
  ERROR_OCCURED_WHILE_FETCHING_DATA: "Error Occured While Fetching Data!",
  ERROR_EDITING_DATA: "Error Editing Data!",
  ERROR_DELETING_DATA: "Error Deleting Data!",
  EDIT_USERS: "Edit Users",
  ADD_USERS: "Add Users",
  WEB_ACCESSES: "Web Accesses",
  CLEAR_FILTER: "Clear Filter",
  SEARCH: "Search",
  SOMETHING_WENT_WRONG: "Something Went Wrong Try Again After Some Time!",
  DATA_UPDATED_SUCCESSFULLY: "Data Updated Successfully.",
};
export { Strings };
